{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace | default "default" | lower }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
data:
{{- toYaml .Values.configMap | nindent 2 }}
{{- end }}
