{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Values.ingress.name | lower }}
  namespace: {{ .Release.Namespace | default "default" | lower }}
spec:
  backend:
    serviceName: {{ default "default" .Values.ingress.backendSvcName | lower }}
    servicePort: {{ default "8080" .Values.ingress.backendSvcPort }}
{{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
{{- end }}
