{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace | default "default" | lower }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
type: Opaque
data:
{{- toYaml .Values.secret | nindent 2 }}
{{- end }}